
services:
  db:
    image: postgis/postgis
    environment:
      POSTGRES_DB: ${POSTGRES_DB}      
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./geoapi
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./geoapi:/code
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Change this to your desired admin email
      PGADMIN_DEFAULT_PASSWORD: admin  # Change this to your desired admin password
    ports:
      - "8080:80"  # Map pgAdmin's default port to a port on your host
    depends_on:
      db:
        condition: service_healthy
    
